### ISSUE TITLE
Popup Window Integration for CIP 30

### ISSUE THREAD

**Issue by edridudi** [Gero-Labs/gerowallet#3]
1. Connect Window Popup - preserve a list of connected websites.
2. Sign Transaction Window Popup
3. Sign Data Window Popup

Take Design from Figma (@adamcazes )

**Comment by adamcazes** [comment]
@eugeniuznagovan section in figma that explains the pop ups design


![Image](https://github.com/Gero-Labs/gerowallet/assets/34624248/df06fe33-17db-493b-b5b3-4dea3f7bb578)
